[package]
name = "palette"
version = "0.5.0" #automatically updated
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
exclude = ["scripts/*", "examples/*", "tests/*", "res/*", ".travis.yml", ".gitignore", "CHANGELOG.md", "CONTRIBUTING.md", "version.sh"]
description = "Convert and manage colors with a focus on correctness, flexibility and ease of use."
documentation = "https://docs.rs/palette/0.5.0/palette/"
repository = "https://github.com/Ogeon/palette"
readme = "README.md"
keywords = ["color", "conversion", "linear", "pixel", "rgb"]
license = "MIT OR Apache-2.0"
edition = "2018"
categories = ["graphics", "multimedia::images", "no-std"]

build = "build/main.rs"

[features]
default = ["named_from_str", "std"]
named_from_str = ["named", "phf", "phf_codegen", "std"]
named = []
random = ["rand"]
serializing = ["serde", "std"]

#ignore in feature test
std = ["approx/std", "num-traits/std"]
libm = ["num-traits/libm"]

[lib]
bench = false

[dependencies]
palette_derive = {version = "0.5.0", path = "../palette_derive"}
num-traits = {version = "0.2", default-features = false}
approx = {version = "0.3", default-features = false}

[dependencies.phf]
version = "0.8"
optional = true

[dependencies.rand]
version = "0.7"
default-features = false
optional = true

[dependencies.serde]
version = "1"
features = ["serde_derive"]
optional = true

[dev-dependencies]
csv = "1"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"

[dev-dependencies.clap]
version = "2"
default-features = false

[dev-dependencies.criterion]
version = "0.3"
default-features = false

[dev-dependencies.image]
version = "0.23"
default-features = false
features = ["png"]

[build-dependencies.phf_codegen]
version = "0.8"
optional = true

[[bench]]
path = "benches/cie.rs"
name = "cie_conversion"
harness = false

[[bench]]
path = "benches/rgb.rs"
name = "rgb_conversion"
harness = false

[[bench]]
path = "benches/matrix.rs"
name = "matrix"
harness = false
